# Generated by Django 2.1.5 on 2019-01-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=100)),
                ('title', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('sentiment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
